[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
implicit_optional = true
show_column_numbers = true

[tool.ruff]
select = ["ALL"]
ignore = [
    "BLE001",
    "C901",
    "COM812",
    "D100",
    "D103",
    "D104",
    "D202",
    "ERA001",
    "E501",
    "EXE002",
    "ERA001",
    "PD901",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR1711",
    "RET501",
    "S101",
    "S603",
]
target-version = "py37"
